"""Generate ir-ring.kicad_sch from a single netlist table.

Every pin is connected by a local label at its connection point, not by wires.
That is valid KiCad and ERC-checkable, and it keeps the netlist in exactly one
place: NETS below. After generation, 08_verify_netlist.py exports the netlist
with kicad-cli and diffs it against NETS, which catches a label on the wrong
pin — something ERC cannot see.
"""
import uuid, os, sys
sys.path.insert(0, os.path.dirname(__file__))
exec(open(os.path.join(os.path.dirname(__file__), "sexp.py")).read())

U = lambda: str(uuid.uuid4())
ROOT = U()

# ---- parts: ref -> (lib_id, value, footprint, LCSC, (x,y)) ----
FPR = "Resistor_SMD:R_0402_1005Metric"
PARTS = {
 "J1":  ("Connector_Generic:Conn_01x05", "JST ZH B5B-ZR", "Connector_JST:JST_ZH_B5B-ZR_1x05_P1.50mm_Vertical", "", (30.48, 50.8)),
 "U1":  ("ir-ring:SY7200A", "SY7200A", "Package_TO_SOT_SMD:SOT-23-6_Handsoldering", "C107309", (91.44, 50.8)),
 "L1":  ("Device:L", "33uH Isat>=500mA", "Inductor_SMD:L_Changjiang_FTC404030S", "", (137.16, 50.8)),
 "D1":  ("Device:D_Schottky", ">=40V 1A", "Diode_SMD:D_SOD-123", "C77343", (172.72, 50.8)),
 "C1":  ("Device:C", "10uF 25V", "Capacitor_SMD:C_0805_2012Metric", "C15850", (208.28, 50.8)),
 "C3":  ("Device:C", "100nF", "Capacitor_SMD:C_0402_1005Metric", "C307331", (233.68, 50.8)),
 "C2":  ("Device:C", "4.7uF 50V", "Capacitor_SMD:C_0805_2012Metric", "C98192", (259.08, 50.8)),
 "R1a": ("Device:R", "4.02R 1%", "Resistor_SMD:R_0805_2012Metric", "C367870", (30.48, 152.4)),
 "R1b": ("Device:R", "4.02R 1%", "Resistor_SMD:R_0805_2012Metric", "C367870", (60.96, 152.4)),
 "Q1":  ("Transistor_FET:Q_NMOS_GSD", "AO3400A", "Package_TO_SOT_SMD:SOT-23", "C20917", (91.44, 152.4)),
 "R2":  ("Device:R", "1M", FPR, "", (129.54, 152.4)),
 "R3":  ("Device:R", "1k", FPR, "C11702", (154.94, 152.4)),
 "R4":  ("Device:R", "100k", FPR, "C25741", (180.34, 152.4)),
 "U2":  ("Device:Q_Photo_NPN", "TEMT6200FX01", "Resistor_SMD:R_0805_2012Metric", "", (218.44, 152.4)),
 "R7":  ("Device:R", "100k", FPR, "C25741", (248.92, 152.4)),
 "R6":  ("Device:R", "100k", FPR, "C25741", (274.32, 152.4)),
}
for i in range(8):
    PARTS[f"D{i+2}"] = ("Device:LED", "IR 850nm 120deg", "ir-ring:LED_3535_JNJ_EW120", "C22447930", (30.48 + i*33.02, 101.6))

# ---- THE netlist: net -> [(ref, pin)] ----
NETS = {
 "+5V":   [("J1","1"),("U1","6"),("L1","1"),("C1","1"),("C3","1"),("R7","1")],
 "GND":   [("J1","2"),("U1","2"),("C1","2"),("C3","2"),("C2","2"),("R1a","2"),("Q1","2"),("R2","2"),("R4","2"),("R6","2")],
 "LDR":   [("J1","3"),("U2","2"),("R6","1")],
 "IL_EN": [("J1","4"),("U1","4"),("R2","1")],
 "WL_EN": [("J1","5"),("R3","1")],
 "SW":    [("U1","1"),("L1","2"),("D1","2")],
 "VOUT":  [("D1","1"),("C2","1"),("U1","5"),("D2","2")],
 "FB":    [("D9","1"),("U1","3"),("R1a","1"),("R1b","1")],
 "R1B_Q": [("R1b","2"),("Q1","3")],
 "Q1_G":  [("R3","2"),("Q1","1"),("R4","1")],
 "U2_C":  [("R7","2"),("U2","1")],
}
for i in range(7):
    NETS[f"STR{i+1}"] = [(f"D{i+2}","1"),(f"D{i+3}","2")]

# ---- symbols ----
def lib_symbol(lib_id):
    lib, name = lib_id.split(":")
    if lib == "ir-ring":
        s = parse(open(os.path.join(os.path.dirname(__file__), "..", "kicad", "ir-ring.kicad_sym")).read())[0]
        s = [e for e in s if isinstance(e, list) and e[0]=="symbol" and e[1]==f'"{name}"'][0]
    else:
        s = find_sym(lib, name)
    assert extends(s) is None, f"{lib_id} uses extends; pick the base symbol"
    s = list(s); s[1] = f'"{lib_id}"'
    return s

used = sorted({p[0] for p in PARTS.values()})
SYMS = {lid: lib_symbol(lid) for lid in used}
PINS = {lid: pins(SYMS[lid]) for lid in used}

# every pin of every part must appear in exactly one net
seen = {}
for net, nodes in NETS.items():
    for n in nodes:
        assert n not in seen, f"{n} in both {seen[n]} and {net}"
        seen[n] = net
for ref, (lid, *_ ) in PARTS.items():
    for num in PINS[lid]:
        assert (ref, num) in seen, f"{ref} pin {num} is in no net"

F = '(effects (font (size 1.27 1.27)))'
FH = '(effects (font (size 1.27 1.27)) (hide yes))'
out = [f'(kicad_sch (version 20250114) (generator "eeschema") (generator_version "9.0") (uuid "{ROOT}") (paper "A3")',
       '(title_block (title "IR ring replacement") (company "anyka-dev") (comment 1 "Generated by ir_design/scripts/07_schematic.py - edit NETS there, not here"))',
       "(lib_symbols"]
out += [dump(SYMS[l], 1) for l in used]
out.append(")")
out.append(f'(text "Label-connected schematic. Every connection is a net label at a pin tip.\\nSource of truth: NETS in 07_schematic.py; 08_verify_netlist.py diffs the exported netlist against it." (exclude_from_sim no) (at 20 20 0) (effects (font (size 1.27 1.27)) (justify left)) (uuid "{U()}"))')

for ref, (lid, val, fp, lcsc, (x, y)) in PARTS.items():
    pl = "".join(f'(pin "{n}" (uuid "{U()}"))' for n in PINS[lid])
    out.append(
      f'(symbol (lib_id "{lid}") (at {x} {y} 0) (unit 1) (exclude_from_sim no) (in_bom yes) (on_board yes) (dnp no) (uuid "{U()}")'
      f'(property "Reference" "{ref}" (at {x+5.08} {y-2.54} 0) (effects (font (size 1.27 1.27)) (justify left)))'
      f'(property "Value" "{val}" (at {x+5.08} {y} 0) (effects (font (size 1.27 1.27)) (justify left)))'
      f'(property "Footprint" "{fp}" (at {x} {y} 0) {FH})'
      f'(property "Datasheet" "~" (at {x} {y} 0) {FH})'
      f'(property "Description" "" (at {x} {y} 0) {FH})'
      f'(property "LCSC" "{lcsc}" (at {x} {y} 0) {FH})'
      f'{pl}(instances (project "ir-ring" (path "/{ROOT}" (reference "{ref}") (unit 1)))))')
    for num, (px, py, ang, _) in PINS[lid].items():
        lx, ly = round(x + px, 4), round(y - py, 4)      # symbol Y is up, schematic Y is down
        la = (ang + 180) % 360                           # point the label away from the body
        just = "left" if la in (0, 90) else "right"
        out.append(f'(label "{seen[(ref,num)]}" (at {lx} {ly} {la}) (effects (font (size 1.27 1.27)) (justify {just} bottom)) (uuid "{U()}"))')

out.append('(sheet_instances (path "/" (page "1")))')
out.append("(embedded_fonts no))")
dst = os.path.join(os.path.dirname(__file__), "..", "kicad", "ir-ring.kicad_sch")
open(dst, "w").write("\n".join(out))
import json
json.dump(NETS, open(os.path.join(os.path.dirname(__file__), "..", "kicad", "nets.json"), "w"), indent=1)
print(f"wrote {os.path.normpath(dst)}: {len(PARTS)} parts, {len(NETS)} nets, {len(seen)} pin connections")
