/**
 * @file hash_utils.h
 * @brief ONVIF-style hash utility functions for password hashing and data integrity
 * @author kkrzysztofik
 * @date 2025
 */

#ifndef ONVIF_HASH_UTILS_H
#define ONVIF_HASH_UTILS_H

#include <stddef.h>
#include <stdint.h>

/* Hash size constants */
#define ONVIF_SHA256_DIGEST_SIZE 32
#define ONVIF_SHA256_HEX_SIZE    65  /* 64 hex chars + null terminator */
#define ONVIF_PASSWORD_HASH_SIZE 128 /* Enough for salt + hash + format info */

/**
 * @brief Compute SHA256 hash of data
 * @param data Input data to hash
 * @param len Length of input data in bytes
 * @param digest Output buffer for 32-byte hash digest
 * @return ONVIF_SUCCESS on success, error code on failure
 */
int onvif_sha256_compute(const uint8_t* data, size_t len, uint8_t digest[ONVIF_SHA256_DIGEST_SIZE]);

/**
 * @brief Convert SHA256 digest to hexadecimal string
 * @param digest Input digest (32 bytes)
 * @param hex_output Output buffer for hex string (must be at least ONVIF_SHA256_HEX_SIZE bytes)
 * @param output_size Size of output buffer
 * @return ONVIF_SUCCESS on success, error code on failure
 */
int onvif_sha256_to_hex(const uint8_t digest[ONVIF_SHA256_DIGEST_SIZE], char* hex_output,
                        size_t output_size);

/**
 * @brief Compute SHA256 hash and output as hexadecimal string
 * @param data Input data to hash
 * @param len Length of input data in bytes
 * @param hex_output Output buffer for hex string (must be at least ONVIF_SHA256_HEX_SIZE bytes)
 * @param output_size Size of output buffer
 * @return ONVIF_SUCCESS on success, error code on failure
 */
int onvif_sha256_compute_hex(const uint8_t* data, size_t len, char* hex_output, size_t output_size);

/**
 * @brief Hash a password with salt for secure storage
 * @param password Plain text password to hash
 * @param hash Output buffer for hashed password (must be at least ONVIF_PASSWORD_HASH_SIZE bytes)
 * @param hash_size Size of hash buffer
 * @return ONVIF_SUCCESS on success, error code on failure
 *
 * The output format is: salt$hash where both salt and hash are hex strings
 */
int onvif_hash_password(const char* password, char* hash, size_t hash_size);

/**
 * @brief Verify a password against a stored hash
 * @param password Plain text password to verify
 * @param hash Stored password hash (in format generated by onvif_hash_password)
 * @return ONVIF_SUCCESS if password matches, ONVIF_ERROR_AUTH_FAILED if not, other error codes on
 * failure
 */
int onvif_verify_password(const char* password, const char* hash);

#endif /* ONVIF_HASH_UTILS_H */
