/**
 * @file onvif_service_common.c
 * @brief Common ONVIF service utility implementations
 * @author kkrzysztofik
 * @date 2025
 */

#include "onvif_service_common.h"

#include <errno.h>
#include <string.h>

#include "core/config/config.h"
#include "core/config/config_runtime.h"
#include "generated/soapH.h"
#include "networking/http/http_constants.h"
#include "networking/http/http_parser.h"
#include "onvif_types.h"
#include "protocol/gsoap/onvif_gsoap_response.h"
#include "protocol/response/onvif_service_handler.h"
#include "utils/error/error_handling.h"
#include "utils/logging/service_logging.h"
#include "utils/memory/smart_response_builder.h"

/* ============================================================================
 * Constants
 * ============================================================================
 */

/* ============================================================================
 * Common Utility Function Implementations
 * ============================================================================
 */

/**
 * @brief Standard parameter validation callback
 */
int onvif_util_validate_standard_parameters(const service_handler_config_t* config, const http_request_t* request, http_response_t* response,
                                            onvif_gsoap_context_t* gsoap_ctx, service_log_context_t* log_ctx, error_context_t* error_ctx) {
  (void)log_ctx;   // Reserved for future logging enhancements
  (void)error_ctx; // Reserved for future error context handling
  // Basic validation - check for required parameters
  if (!config || !request || !response || !gsoap_ctx) {
    return ONVIF_ERROR;
  }
  return ONVIF_SUCCESS;
}

/**
 * @brief Standard post-processing callback
 */
int onvif_util_standard_post_process(http_response_t* response, service_log_context_t* log_ctx) {
  (void)log_ctx; // Reserved for future logging enhancements
  // Standard post-processing - ensure response is properly formatted
  if (!response) {
    return ONVIF_ERROR;
  }

  // Set default content type if not set
  if (!response->content_type) {
    response->content_type = "application/soap+xml";
  }

  // Set default status code if not set
  if (response->status_code == 0) {
    response->status_code = HTTP_STATUS_OK;
  }

  return ONVIF_SUCCESS;
}

/**
 * @brief Generic ONVIF service handler with enhanced callback pattern
 */
int onvif_util_handle_service_request(const service_handler_config_t* config, const http_request_t* request, http_response_t* response,
                                      onvif_gsoap_context_t* gsoap_ctx, const onvif_service_operation_t* operation,
                                      int (*soap_callback)(struct soap* soap, void* user_data), void* callback_data) {
  if (!config || !request || !response || !gsoap_ctx || !operation) {
    return ONVIF_ERROR;
  }

  // Initialize contexts
  service_log_context_t log_ctx;
  service_log_init_context(&log_ctx, operation->service_name, operation->operation_name, SERVICE_LOG_INFO);

  error_context_t error_ctx;
  error_context_init(&error_ctx, operation->service_name, operation->operation_name, operation->operation_context);

  // Validate parameters
  if (operation->callbacks.validate_parameters) {
    int result = operation->callbacks.validate_parameters(config, request, response, gsoap_ctx, &log_ctx, &error_ctx);
    if (result != ONVIF_SUCCESS) {
      return result;
    }
  }

  // Execute business logic
  int business_logic_result = ONVIF_SUCCESS;
  if (operation->callbacks.execute_business_logic) {
    business_logic_result = operation->callbacks.execute_business_logic(config, request, response, gsoap_ctx, &log_ctx, &error_ctx, callback_data);

    // If SOAP fault was generated by error handler, skip response generation and return success
    if (business_logic_result == ONVIF_ERROR_SOAP_FAULT) {
      // Response is already set by error_handle_pattern(), just return
      return ONVIF_SUCCESS;
    }

    // For other errors, return immediately
    if (business_logic_result != ONVIF_SUCCESS) {
      return business_logic_result;
    }
  }

  // Generate SOAP response using callback (only if business logic didn't already set response body)
  if (soap_callback && !response->body) {
    int result = onvif_gsoap_generate_response_with_callback(gsoap_ctx, soap_callback, callback_data);
    if (result != ONVIF_SUCCESS) {
      service_log_operation_failure(&log_ctx, "soap_response_generation", result, "Failed to generate SOAP response");
      return result;
    }

    // Copy the generated SOAP response to the HTTP response
    const char* soap_response = onvif_gsoap_get_response_data(gsoap_ctx);
    if (soap_response) {
      // Use smart_response_build_with_dynamic_buffer to properly copy the response
      if (smart_response_build_with_dynamic_buffer(response, soap_response) == ONVIF_SUCCESS) {
        response->status_code = HTTP_STATUS_OK;
      } else {
        // Fallback: assign pointer directly (may be temporary)
        // NOLINTNEXTLINE(cppcoreguidelines-pro-type-const-cast) - Temporary pointer assignment
        response->body = (char*)soap_response;
        response->body_length = strlen(soap_response);
        response->status_code = HTTP_STATUS_OK;
      }
    }
  }

  // Post-process response
  if (operation->callbacks.post_process_response) {
    int result = operation->callbacks.post_process_response(response, &log_ctx);
    if (result != ONVIF_SUCCESS) {
      return result;
    }
  }

  return ONVIF_SUCCESS;
}

/* ============================================================================
 * Configuration Helper Functions
 * ============================================================================ */

/* ============================================================================
 * Service Type Conversion Functions
 * ============================================================================ */

/**
 * @brief Convert service type to string
 */
const char* onvif_service_type_to_string(onvif_service_type_t service) {
  switch (service) {
  case ONVIF_SERVICE_DEVICE:
    return "Device";
  case ONVIF_SERVICE_MEDIA:
    return "Media";
  case ONVIF_SERVICE_PTZ:
    return "PTZ";
  case ONVIF_SERVICE_IMAGING:
    return "Imaging";
  case ONVIF_SERVICE_SNAPSHOT:
    return "Snapshot";
  default:
    return "Unknown";
  }
}

/**
 * @brief Convert action type to string
 */
