/**
 * @file onvif_types.h
 * @brief Shared ONVIF type definitions for the daemon
 * @author kkrzysztofik
 * @date 2025
 *
 */

#ifndef ONVIF_TYPES_H
#define ONVIF_TYPES_H

#include <stdbool.h>

/* ONVIF service types */
typedef enum {
  ONVIF_SERVICE_DEVICE = 0,
  ONVIF_SERVICE_MEDIA,
  ONVIF_SERVICE_PTZ,
  ONVIF_SERVICE_IMAGING
} onvif_service_type_t;

/* ONVIF action types - comprehensive list for all services */
typedef enum {
  ONVIF_ACTION_UNKNOWN = -1,
  /* Device service actions */
  ONVIF_ACTION_GET_CAPABILITIES = 0,
  ONVIF_ACTION_GET_DEVICE_INFORMATION,
  ONVIF_ACTION_GET_SYSTEM_DATE_AND_TIME,
  ONVIF_ACTION_SET_SYSTEM_DATE_AND_TIME,
  ONVIF_ACTION_GET_SERVICES,
  ONVIF_ACTION_GET_SYSTEM_LOGGING,
  ONVIF_ACTION_GET_SCOPES,
  ONVIF_ACTION_SET_SCOPES,
  ONVIF_ACTION_ADD_SCOPES,
  ONVIF_ACTION_REMOVE_SCOPES,
  ONVIF_ACTION_GET_DISCOVERY_MODE,
  ONVIF_ACTION_SET_DISCOVERY_MODE,
  ONVIF_ACTION_GET_REMOTE_DISCOVERY_MODE,
  ONVIF_ACTION_SET_REMOTE_DISCOVERY_MODE,
  ONVIF_ACTION_GET_DPADDRESSES,
  ONVIF_ACTION_SET_DPADDRESSES,
  ONVIF_ACTION_GET_NETWORK_INTERFACES,
  ONVIF_ACTION_SET_NETWORK_INTERFACES,
  ONVIF_ACTION_GET_NETWORK_PROTOCOLS,
  ONVIF_ACTION_SET_NETWORK_PROTOCOLS,
  ONVIF_ACTION_GET_NETWORK_DEFAULT_GATEWAY,
  ONVIF_ACTION_SET_NETWORK_DEFAULT_GATEWAY,
  ONVIF_ACTION_GET_ZERO_CONFIGURATION,
  ONVIF_ACTION_SET_ZERO_CONFIGURATION,
  ONVIF_ACTION_GET_IP_ADDRESS_FILTER,
  ONVIF_ACTION_SET_IP_ADDRESS_FILTER,
  ONVIF_ACTION_ADD_IP_ADDRESS_FILTER,
  ONVIF_ACTION_REMOVE_IP_ADDRESS_FILTER,
  ONVIF_ACTION_GET_ACCESS_POLICY,
  ONVIF_ACTION_SET_ACCESS_POLICY,
  ONVIF_ACTION_CREATE_CERTIFICATE,
  ONVIF_ACTION_GET_CERTIFICATES,
  ONVIF_ACTION_GET_CERTIFICATE_INFORMATION,
  ONVIF_ACTION_SET_CERTIFICATE,
  ONVIF_ACTION_DELETE_CERTIFICATE,
  ONVIF_ACTION_GET_PKCS_10_REQUEST,
  ONVIF_ACTION_LOAD_CERTIFICATE_WITH_PRIVATE_KEY,
  ONVIF_ACTION_GET_CLIENT_CERTIFICATE_MODE,
  ONVIF_ACTION_SET_CLIENT_CERTIFICATE_MODE,
  ONVIF_ACTION_GET_RELAY_OUTPUTS,
  ONVIF_ACTION_SET_RELAY_OUTPUT_SETTINGS,
  ONVIF_ACTION_SET_RELAY_OUTPUT_STATE,
  ONVIF_ACTION_GET_SERVICE_CAPABILITIES,
  ONVIF_ACTION_SYSTEM_REBOOT,

  /* Media service actions */
  ONVIF_ACTION_GET_VIDEO_SOURCES,
  ONVIF_ACTION_GET_VIDEO_OUTPUTS,
  ONVIF_ACTION_GET_AUDIO_SOURCES,
  ONVIF_ACTION_GET_AUDIO_OUTPUTS,
  ONVIF_ACTION_GET_AUDIO_SOURCE_CONFIGURATIONS,
  ONVIF_ACTION_GET_AUDIO_OUTPUT_CONFIGURATIONS,
  ONVIF_ACTION_GET_VIDEO_SOURCE_CONFIGURATIONS,
  ONVIF_ACTION_GET_VIDEO_OUTPUT_CONFIGURATIONS,
  ONVIF_ACTION_GET_METADATA_CONFIGURATIONS,
  ONVIF_ACTION_SET_METADATA_CONFIGURATION,
  ONVIF_ACTION_GET_COMPOSITE_CONFIGURATIONS,
  ONVIF_ACTION_GET_AUDIO_DECODER_CONFIGURATIONS,
  ONVIF_ACTION_GET_VIDEO_ANALYTICS_CONFIGURATIONS,
  ONVIF_ACTION_GET_PTZ_CONFIGURATIONS,
  ONVIF_ACTION_SET_VIDEO_SOURCE_CONFIGURATION,
  ONVIF_ACTION_SET_VIDEO_ENCODER_CONFIGURATION,
  ONVIF_ACTION_SET_AUDIO_SOURCE_CONFIGURATION,
  ONVIF_ACTION_SET_AUDIO_ENCODER_CONFIGURATION,
  ONVIF_ACTION_GET_VIDEO_SOURCE_CONFIGURATION,
  ONVIF_ACTION_GET_VIDEO_OUTPUT_CONFIGURATION,
  ONVIF_ACTION_GET_AUDIO_SOURCE_CONFIGURATION,
  ONVIF_ACTION_GET_AUDIO_OUTPUT_CONFIGURATION,
  ONVIF_ACTION_GET_METADATA_CONFIGURATION,
  ONVIF_ACTION_GET_COMPOSITE_CONFIGURATION,
  ONVIF_ACTION_GET_AUDIO_DECODER_CONFIGURATION,
  ONVIF_ACTION_GET_VIDEO_ANALYTICS_CONFIGURATION,
  ONVIF_ACTION_GET_PTZ_CONFIGURATION,
  ONVIF_ACTION_GET_VIDEO_SOURCE_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_VIDEO_OUTPUT_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_AUDIO_SOURCE_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_AUDIO_OUTPUT_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_METADATA_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_COMPOSITE_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_AUDIO_DECODER_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_VIDEO_ANALYTICS_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_PTZ_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_GET_GUARANTEED_VIDEO_ITEM_BOUNDS,
  ONVIF_ACTION_GET_STREAM_URI,
  ONVIF_ACTION_GET_SNAPSHOT_URI,
  ONVIF_ACTION_START_MULTICAST_STREAMING,
  ONVIF_ACTION_STOP_MULTICAST_STREAMING,
  ONVIF_ACTION_GET_PROFILES,
  ONVIF_ACTION_CREATE_PROFILE,
  ONVIF_ACTION_DELETE_PROFILE,
  ONVIF_ACTION_ADD_PROFILE,
  ONVIF_ACTION_REMOVE_PROFILE,
  ONVIF_ACTION_GET_VIDEO_SOURCE_MODE,
  ONVIF_ACTION_SET_VIDEO_SOURCE_MODE,
  ONVIF_ACTION_GET_OSD,
  ONVIF_ACTION_GET_OSD_OPTIONS,
  ONVIF_ACTION_SET_OSD,
  ONVIF_ACTION_CREATE_OSD,
  ONVIF_ACTION_DELETE_OSD,

  /* PTZ service actions */
  ONVIF_ACTION_GET_MOVE_OPTIONS,
  ONVIF_ACTION_GET_STATUS,
  ONVIF_ACTION_GET_CONFIGURATION,
  ONVIF_ACTION_GET_CONFIGURATIONS,
  ONVIF_ACTION_GET_COMPATIBLE_CONFIGURATIONS,
  ONVIF_ACTION_SET_CONFIGURATION,
  ONVIF_ACTION_GET_CONFIGURATION_OPTIONS,
  ONVIF_ACTION_STOP,
  ONVIF_ACTION_ABSOLUTE_MOVE,
  ONVIF_ACTION_RELATIVE_MOVE,
  ONVIF_ACTION_CONTINUOUS_MOVE,
  ONVIF_ACTION_GET_PRESETS,
  ONVIF_ACTION_SET_PRESET,
  ONVIF_ACTION_REMOVE_PRESET,
  ONVIF_ACTION_GOTO_PRESET,

  /* Imaging service actions */
  ONVIF_ACTION_GET_IMAGING_SETTINGS,
  ONVIF_ACTION_SET_IMAGING_SETTINGS,
  ONVIF_ACTION_GET_OPTIONS
} onvif_action_type_t;

#endif /* ONVIF_TYPES_H */
