#!/bin/sh
#

    [ -f /mnt/anyka_hack/common.sh ] && . /mnt/anyka_hack/common.sh

if [ -f /data/www/index.html ]; then
    . /data/www/cgi-bin/header
else
    . /mnt/anyka_hack/web_interface/www/cgi-bin/header
fi
if [ -f /mnt/tmp/token.txt ] && [ "$token" = "$(readline 1 /mnt/tmp/token.txt)" ]; then
if [ "$scan" = "true" ]; then
sh /mnt/anyka_hack/ffmpeg/wrap_mp4.sh
cat <<EOT
<html>
    <head>
        <meta http-equiv="refresh" content="0; url=/cgi-bin/legacy/events?token=$token" />
    </head>
    <body>
        <a href="/cgi-bin/legacy/events?token=$token">Legacy WebUI</a>
    </body>
</html>
EOT
else
cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - Legacy WebUI</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<div class="topnav">
  <a href="/cgi-bin/legacy/webui?token=$token">Home</a>
  <a href="/cgi-bin/legacy/settings?token=$token">Settings</a>
  <a href="/cgi-bin/legacy/system?token=$token">System</a>
  <a class="active" href="/cgi-bin/legacy/events?token=$token">Events</a>
  <a href="/cgi-bin/legacy/login">Exit</a>
  <a href="/cgi-bin/webui_onvif?token=$token" style="float: right; background-color: #4CAF50;">ONVIF Interface</a>
</div>

<section>

<div class="card">
<h2>$file.mp4</h2>
<video controls width="600">
  <source src="/video/$file.mp4" type="video/mp4" />
</video>
<br>
</div>
</section>

</body>
</html>
EOT
fi
else
    if [ -f /data/www/index.html ]; then
        . /data/www/cgi-bin/footer
    else
        . /mnt/anyka_hack/web_interface/www/cgi-bin/footer
    fi
fi
