//! FFI bindings to Anyka SDK.
//!
//! This module provides Rust bindings to the Anyka SDK C libraries.
//! When cross-compiling for ARM, actual FFI bindings are generated by bindgen.
//! For native builds (testing), stub implementations are provided.

mod anyka_sdk;

pub use anyka_sdk::*;

// Re-export common types
#[cfg(not(use_stubs))]
pub use generated::*;

#[cfg(not(use_stubs))]
mod generated {
    //! Generated bindings from Anyka SDK headers.
    //!
    //! These are only available when cross-compiling for ARM target.

    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Include consolidated generated bindings
    include!(concat!(env!("OUT_DIR"), "/anyka_bindings.rs"));
}

// Stub types for native builds (testing)
#[cfg(use_stubs)]
pub mod stubs {
    //! Stub types for testing without actual hardware.
    //!
    //! These types mirror the Anyka SDK types but are available
    //! on all platforms for testing purposes.

    /// Return codes matching Anyka SDK
    pub const AK_SUCCESS: i32 = 0;
    pub const AK_FAILED: i32 = -1;
    pub const AK_FALSE: i32 = 0;
    pub const AK_TRUE: i32 = 1;

    /// Log levels matching Anyka SDK
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum LogLevel {
        Reserved = 0,
        Error = 1,
        Warning = 2,
        Notice = 3,
        Normal = 4,
        Info = 5,
        Debug = 6,
    }

    /// Video device type
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum VideoDevType {
        Dev0 = 0,
    }

    /// Video channel
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum VideoChannel {
        Main = 0,
        Sub = 1,
    }

    /// Video resolution
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct VideoResolution {
        pub width: i32,
        pub height: i32,
        pub max_width: i32,
        pub max_height: i32,
    }

    /// Encode output type
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum EncodeOutputType {
        H264 = 0,
        Mjpeg = 1,
        Hevc = 2,
    }

    /// Bitrate control mode
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum BitrateCtrlMode {
        Cbr = 0,
        Vbr = 1,
    }

    /// Profile mode
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum ProfileMode {
        Main = 0,
        High = 1,
        Base = 2,
        HevcMain = 3,
        HevcMainStill = 4,
    }

    /// Encode parameters
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct EncodeParam {
        pub width: u32,
        pub height: u32,
        pub minqp: i32,
        pub maxqp: i32,
        pub fps: i32,
        pub goplen: i32,
        pub bps: i32,
        pub profile: i32,
        pub use_chn: i32,
        pub enc_grp: i32,
        pub br_mode: i32,
        pub enc_out_type: i32,
    }

    /// Audio parameters
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct AudioParam {
        pub sample_rate: u32,
        pub channel_num: u32,
        pub sample_bits: u32,
        pub type_: i32,
    }

    /// PTZ device
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum PtzDevice {
        Horizontal = 0,
        Vertical = 1,
    }

    /// PTZ turn direction
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum PtzTurnDirection {
        Reserved = 0,
        Left = 1,
        Right = 2,
        Up = 3,
        Down = 4,
    }
}

#[cfg(use_stubs)]
pub use stubs::*;
