//! FFI bindings to Anyka SDK.
//!
//! This module provides Rust bindings to the Anyka SDK C libraries.
//! When cross-compiling for ARM, actual FFI bindings are generated by bindgen.
//! For native builds (testing), stub implementations are provided.

mod anyka_sdk;
pub mod audio;
pub mod video;

pub use anyka_sdk::*;
pub use audio::{
    AudioEncoderHandle, AudioInputHandle, audio_encoder_open, audio_encoder_set_config,
    audio_input_open, audio_input_set_volume,
};
pub use video::{
    VideoEncoderHandle, VideoInputHandle, video_encoder_open, video_encoder_request_idr,
    video_encoder_set_rc, video_input_get_sensor_resolution, video_input_open,
    video_input_set_channel_attr,
};

// Re-export common types
#[cfg(not(use_stubs))]
pub use generated::*;

#[cfg(not(use_stubs))]
mod generated {
    //! Generated bindings from Anyka SDK headers.
    //!
    //! These are only available when cross-compiling for ARM target.

    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Include consolidated generated bindings
    include!(concat!(env!("OUT_DIR"), "/anyka_bindings.rs"));
}

// Stub types for native builds (testing)
#[cfg(use_stubs)]
pub mod stubs {
    //! Stub types for testing without actual hardware.
    //!
    //! These types mirror the Anyka SDK types but are available
    //! on all platforms for testing purposes.

    /// Return codes matching Anyka SDK
    pub const AK_SUCCESS: i32 = 0;
    pub const AK_FAILED: i32 = -1;
    pub const AK_FALSE: i32 = 0;
    pub const AK_TRUE: i32 = 1;

    /// Video device type
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum VideoDevType {
        Dev0 = 0,
    }

    /// Video resolution
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct VideoResolution {
        pub width: i32,
        pub height: i32,
        pub max_width: i32,
        pub max_height: i32,
    }

    /// Encode output type
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum EncodeOutputType {
        H264 = 0,
        Mjpeg = 1,
        Hevc = 2,
    }

    /// Bitrate control mode
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum BitrateCtrlMode {
        Cbr = 0,
        Vbr = 1,
    }

    /// Profile mode
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum ProfileMode {
        Main = 0,
        High = 1,
        Base = 2,
        HevcMain = 3,
        HevcMainStill = 4,
    }

    /// Encode parameters
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct EncodeParam {
        pub width: u32,
        pub height: u32,
        pub minqp: i32,
        pub maxqp: i32,
        pub fps: i32,
        pub goplen: i32,
        pub bps: i32,
        pub profile: i32,
        pub use_chn: i32,
        pub enc_grp: i32,
        pub br_mode: i32,
        pub enc_out_type: i32,
    }

    /// Audio parameters
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct AudioParam {
        pub sample_rate: u32,
        pub channel_num: u32,
        pub sample_bits: u32,
        pub type_: i32,
    }

    /// PTZ device
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum PtzDevice {
        Horizontal = 0,
        Vertical = 1,
    }

    /// PTZ turn direction
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum PtzTurnDirection {
        Reserved = 0,
        Left = 1,
        Right = 2,
        Up = 3,
        Down = 4,
    }

    /// Video channel attributes
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct VideoChannelAttr {
        pub crop: CropInfo,
        pub res: [VideoResolution; 2], // VIDEO_CHN_NUM = 2 (MAIN, SUB)
    }

    /// Crop information
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct CropInfo {
        pub left: i32,
        pub top: i32,
        pub width: i32,
        pub height: i32,
    }

    /// PCM parameters for audio input
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct PcmParam {
        pub sample_rate: u32,
        pub sample_bits: u32,
        pub channel_num: u32,
    }

    /// Audio encoder attributes
    #[repr(C)]
    #[derive(Debug, Clone, Copy, Default)]
    pub struct AencAttr {
        pub aac_head: i32, // enum aenc_aac_attr
    }
}

#[cfg(use_stubs)]
pub use stubs::*;

// Type aliases for consistency with generated bindings (snake_case)
#[cfg(use_stubs)]
pub type video_channel_attr = stubs::VideoChannelAttr;
#[cfg(use_stubs)]
pub type pcm_param = stubs::PcmParam;
#[cfg(use_stubs)]
pub type aenc_attr = stubs::AencAttr;
#[cfg(use_stubs)]
pub type encode_param = stubs::EncodeParam;
#[cfg(use_stubs)]
pub type video_dev_type = stubs::VideoDevType;
#[cfg(use_stubs)]
pub type video_resolution = stubs::VideoResolution;
#[cfg(use_stubs)]
pub type audio_param = stubs::AudioParam;
