#!/bin/sh

[ -f /mnt/anyka_hack/common.sh ] && . /mnt/anyka_hack/common.sh

if [ -f /data/www/index.html ]; then
  . /data/www/cgi-bin/header
else
    . /mnt/anyka_hack/web_interface/www/cgi-bin/header
fi
if [ -f /mnt/tmp/token.txt ] && [ "$token" = "$(readline 1 /mnt/tmp/token.txt)" ]; then
#import settings
. /data/gergesettings.txt
message_banner=""

if [ -f /mnt/anyka_hack/web_interface/www/index.html ]; then
  if [ "$md_record_sec" = 0 ]; then
    message_banner="<div class=\"banner\">Motion recording is disabled!<br><br><button onclick=\"window.location.href='settings?token=$token'\">Turn on in Settings</button></div>"
  fi

  filelist="<div class=\"card\"><h2>Recorded Events</h2><table style=\"margin: 0px auto\"><tr>"
  videofiles=$(ls /mnt/anyka_hack/web_interface/www/video/*.mp4 2>/dev/null)

  for i in $videofiles; do
    filename=$(echo "$i" | sed 's/\.mp4$//')
    filename=$(basename "$filename")
    filelist="$filelist<tr><th>$filename.mp4</th>"
    filelist="$filelist<th><button onclick=\"window.location.href='video?token=$token&file=$filename'\">View Event</button></th>"
    filelist="$filelist<th><button onclick=\"window.location.href='del_video.sh?token=$token&file=$filename'\">Delete</button></th></tr>"
  done
  filelist="$filelist</table>Scan for new files with ffmpeg (stops main app to free memory while running)<br><br><button onclick=\"window.location.href='video?token=$token&scan=true'\">Run FFMPEG</button><br><br></div>"

else
  message_banner="<div class=\"banner\">No SD card Inserted!<br><br><button onclick=\"window.location.href='webui?token=$token'\"> Back </button></div>"
  filelist=""
fi

cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - WebUI</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<div class="topnav">
  <a href="/cgi-bin/webui?token=$token">Home</a>
  <a href="/cgi-bin/settings?token=$token">Settings</a>
  <a href="/cgi-bin/system?token=$token">System</a>
  <a class="active" href="/cgi-bin/events?token=$token">Events</a>
  <a href="/cgi-bin/login">Exit</a>
</div>

<section>
$message_banner
$filelist

</section>
</body>
</html>
EOT
else
  if [ -f /data/www/index.html ]; then
    . /data/www/cgi-bin/footer
  else
    . /mnt/anyka_hack/web_interface/www/cgi-bin/footer
  fi
fi
