#!/bin/sh

readline() {
  linetoread=$1
  file=$2
  sed ${linetoread}q;d $file
}
#https://www.freecodecamp.org/news/url-encoded-characters-reference/
QUERY_STRING="${QUERY_STRING//&/ }"
query_out=""
for element in $QUERY_STRING; do
  splitelement=$(echo "$element" | sed 's/%/ %/g')
  for i in $splitelement; do
    firstchar=$(echo "$i" | cut -c1)
    if [ "$firstchar" = "%" ]; then
      hex=$(echo "$i" | cut -c2-3)
      rest=$(echo "$i" | cut -c4-)
      query_out="$query_out"$(printf "\x$hex")"$rest"
    else
      query_out="$query_out$i"
    fi
  done
  query_out="$query_out "
done
QUERY_STRING="$query_out"

for i in $QUERY_STRING; do
  eval "$i"
done


echo "Content-type: text/html"
echo ""
